# Generated by Django 4.2 on 2023-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='undefined', max_length=50),
        ),
    ]
