# Generated by Django 4.2 on 2023-04-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_post_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Practice',
        ),
    ]
