# Generated by Django 4.2 on 2023-04-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
